### ISSUE TITLE
Get rid of judgement :disposition number

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctim#122]
Just use names.

**Comment by craigbro** [comment]
Yah, and put the stirng value "High" and whatever in the :disposition field.

Aka, drop :disposition and rename :disposition_name to :disposition

**Comment by polygloton** [comment]
Should this be inn the Feb-2017 MVP?

**Comment by polygloton** [comment]
We probably shouldn't do this.  Conflicts with #142.
