### ISSUE TITLE
Github markdown parser can't process generated structure docs

### ISSUE THREAD

**Issue by folbricht** [threatgrid/ctim#146]
The generated structure docs like https://github.com/threatgrid/ctim/blob/master/doc/structures/sighting.md, when viewed online come out with raw markdown.

![screen shot 2017-03-30 at 3 18 43 pm](https://cloud.githubusercontent.com/assets/3505107/24527395/20756c50-155f-11e7-8046-56a7085838fc.png)

Most likely caused by several of these links throughout the documents
```html
<a name="top"/>
```

**Comment by polygloton** [comment]
These are the docs generated by the flanders+ctim "lein doc" code.

**Comment by polygloton** [comment]
I'm pretty sure it used to work, so maybe something changed on the github side.
