### ISSUE TITLE
Don't require "type" when POSTing

### ISSUE THREAD

**Issue by folbricht** [threatgrid/ctim#147]
When POSTing a Sighting, `type` is optional since it's clear what it should contains since the endpoint is /ctia/sighting

With Actor, `type` is a required field which is inconsistent and unnecessary. Please make `type` optional for all New* objects.
```json
{"errors":{"type":"(not (#{\"actor\"} \"\"))"}}
```

**Comment by polygloton** [comment]
This is a bug.
