### ISSUE TITLE
Malware abstraction level

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctim#197]
The Malware schema needs an `:abstraction_level`, similar to the one we added for Attack Patterns.

The valid levels of abstraction for Malware are:
```
#{"family"
  "variant"
  "version"}
```

**Comment by gbuisson** [comment]
do you need it `optional` or `required`?
if it is required what should be the default  ?

**Comment by msprunck** [comment]
Closed by #203

**Comment by gbuisson** [comment]
for QA:

On CTIA, malware objects now support an `abstraction_level` field,
when posting/updating a malware one can set this field.

**Comment by hshahman** [comment]
Verified in rel-v1.1
