### ISSUE TITLE
Ensure that SMA Tracking API's mid array is associated with sightings and incidents

### ISSUE THREAD

**Issue by bmaloney** [threatgrid/ctim#220]
Apologies for this being vague and perhaps already complete. There was a flurry of cross-channel HipChat conversations during the week of Nov 11. 2018 between @deandebeer @msprunck @gbuisson and @jbouwman regarding the unique identifier needed for associating an email with both a sighting and an incident. We intend to release the email/SMA integration in mid December 2018 - thus the chatter.

To support our use cases, we need to be able to associate emails with sightings and incidents. My assumption is that this is done via mid (message ID). My assumption may be incorrect and our use cases may already be supported.

I've read through:
- SMA Module: https://github.com/threatgrid/iroh/blob/master/int-modules/sma-module/doc/developer.md
- CTIM Incident Object: https://github.com/threatgrid/ctim/blob/master/doc/structures/incident.md 
- Simplified incident JSON: https://github.com/threatgrid/ctim/blob/master/doc/json/incident.json
- CTIM Sighting Object: https://github.com/threatgrid/ctim/blob/master/doc/structures/sighting.md
- EMail_API_Tracking_V2.txt from Suresh:
[EMail_API_Tracking_V2.txt](https://github.com/threatgrid/ctim/files/2589840/EMail_API_Tracking_V2.txt)
- message PDF from Matt:
[message.pdf](https://github.com/threatgrid/ctim/files/2589841/message.pdf)

I believe that the mid array values, being the same as ciscoMid, will provide a unique identifier for a message (email). According to SMA Module docs (https://github.com/threatgrid/iroh/blob/master/int-modules/sma-module/doc/developer.md), mid array is present in the response object for every query documented. Use case examples associated with said responses are:
- Search all messages containing an attachment with SHA-256 f4e9b6eb60daba8747c8dd072aba827e94fa78c6af154ecfc218e7eeea8c1728
- Search all messages with the sender IP 10.76.70.111
- Search all messages with vm30bsd0004.ibqa as the sender domain
- Search all messages containing an attachment with the filename win32server.exe
- Search all messages with the Message-ID header 3aqsgl$38@allison.qa
- Search all messages with the subject test of v 1 a g r a
- Search all messages where test_quar_in@vm30bsd0004.ibqa is the sender

However, I do not see mids present in the generated sighting objects associated with each response. **Do we need it within generated sightings?**

There was some confusion between mid (message ID) and Message-ID header. Message-ID header is not available in the aforementioned response objects but Matt has requested it and Suresh has responded with:
> Will check for backend feasibility and if feasible will be adding the same in the next release of product - 13.0

I'm not sure what advantages Message-ID header has over the mid values

mid is an array which confused me at first. However, I found two use cases for an email having multiple mids:
1. As documented: Message Status Splintered: When the MID of a message is split into multiple MIDs having multiple final states
2. A bounced email appears to have an mid for the incoming email and an mid for the email sent by the system to the recipient notifying them of the bounce

**Comment by msprunck** [comment]
I changed my mind. The `cisco_mid` does not define the target itself. It would be better to add them to the observed relations.

Example:

```clojure
{:description "Incoming message (Quarantined by Multiple Engines) Sighting"
  :confidence "High"
  :severity "Low"
  :count 1
  :observables [{:type "email_messageid" :value "3aqsgl$38@allison.qa"}]
  :observed_time {:start_time "2018-05-25T12:59:59+00:00"
                  :end_time "2018-05-25T12:59:59+00:00"}
  :sensor "process.email-service"
  :internal true
  :resolution "contained"
  :targets [{:type "email"
             :observed_time {:start_time "2018-05-25T12:59:59+00:00"}
             :observables [{:type "email" :value "431@vm30bsd0004.ibqa"}]
  :source "SMA Tracking API"
  :type "sighting"
  :schema_version "1.0.0"
  :id "transient:00000000-0000-0000-0000-000000000006"}]
  :relations [{:origin "SMA Enrichment Module"
               :relation "Used_By"
               :source {:type "ip" :value "10.76.70.111"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Used_By"
               :source {:type "domain" :value "vm30bsd0004.ibqa"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Sent_By"
               :source {:type "cisco_mid" :value "3887"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Sent_By"
               :source {:type "cisco_mid" :value "3894"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Sent_By"
               :source {:type "cisco_mid" :value "3897"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Sent_By"
               :source {:type "cisco_mid" :value "3902"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}
              {:origin "SMA Enrichment Module"
               :relation "Sent_By"
               :source {:type "cisco_mid" :value "3911"}
               :related {:type "email" :value "test_quar_in@vm30bsd0004.ibqa"}}]}
```

**Comment by gbuisson** [comment]
@bmaloney closing this and reopening in our internal repo

https://github.com/threatgrid/iroh/issues/2277
