### ISSUE TITLE
Judgement Schema fails flanders spec for def-entity-type

### ISSUE THREAD

**Issue by egierach** [threatgrid/ctim#256]
The description for the Judgement type needs to be a map of `{:description "the description"}` rather than just a string.

Edit: we found the same issue with the Verdict type.

**Comment by msprunck** [comment]
The definition of the `def-entity-type` macro handles a description as a string or a map. See here https://github.com/threatgrid/flanders/blob/master/src/flanders/core.cljc#L204. The current definition of Judgement and Verdict is correct.

**Comment by noprompt** [comment]
This problem has been resolved in Flanders `v0.1.19`.
