### ISSUE TITLE
Add cyber kill chain to TTP schema

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctim#36]
Add cyber kill chain to TTP schema.

**Comment by craigbro** [comment]
Why did you make this a base entity?  Is this ever manipulated as a top level object?

**Comment by saintx** [comment]
http://stixproject.github.io/data-model/1.0/stixCommon/KillChainType/ specifies an ID field.  What is the recommended way, if not to extend the BaseEntity, to give an object an ID in CTIM?
