### ISSUE TITLE
Consider adding trend_micro_id as an observable type

### ISSUE THREAD

**Issue by ceilingduster** [threatgrid/ctim#375]
Necessary to add support for third party host ID observables for Trend Micro

This request is similar to the support added for defender and sentinel one.

https://github.com/threatgrid/ctim/pull/310

**Comment by gbuisson** [comment]
The Data services team will handle it @ereteog

**Comment by maimahes** [comment]
Is this task complete and available in SecureX TEST ?  noticing some issue while testing workflows for trend micro ..

**Comment by ereteog** [comment]
@maimahes can you detail the issue, please?
