### ISSUE TITLE
Actor: make actor_type optional. 

### ISSUE THREAD

**Issue by samwagg** [threatgrid/ctim#381]
`actor_type` [is required](https://github.com/threatgrid/ctim/blob/master/doc/structures/actor.md), but we want to ingest Mitre ATT&CK Groups, which don't include data to populate this field. [E.g.](https://github.com/mitre/cti/blob/master/enterprise-attack/intrusion-set/intrusion-set--00f67a77-86a4-4adf-be26-1a54fc713340.json)

Is it safe to make this field optional? We know that public CTIA does not currently have any Actors loaded.

**Comment by ereteog** [comment]
Since we never used actors, I guess that hydrant will be the first user, so I do not see any issue.
However, to help you make a thoughtful decision about that, once done the way back is nearly impossible since we might have actors without `actor_type` sent by other CTIM producers (like modules).
@gbuisson @msprunck I lack of history about this entity type, wdyt?

**Comment by samwagg** [comment]
> FORGET what I said. I think that we might update our list of actor type and include Unknown like in [stix 2](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_tqbl8z36yoir). Then if you have no information about it, you can explicitly express it. I like stix documentation about threat actors [here](https://oasis-open.github.io/cti-documentation/examples/identifying-a-threat-actor-profile)

My only concern is that "unknown" indicates that the Actor Type is generally unknown to the threat intel community. Whereas the real situation in this case is that ATT&CK Groups just don't include this data. The STIX definition of unknown is: "There is not enough information available to determine the type of threat actor." This is nitpicky, but I think there might be a meaningful difference.

**Comment by ereteog** [comment]
Hum you right, then you can go back to my first comment :-).
Let's wait a little bit for Matt and GB feedbacks.

**Comment by msprunck** [comment]
This field is optional in [stix 1.2](https://stixproject.github.io/data-model/1.2/ta/ThreatActorType/) and [stix 2](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_2wowmlcbkqst). I would set it as optional. In addition, like Stix, I would convert it to a collection and rename it to `actor_types`.

**Comment by samwagg** [comment]
I opened a [separate issue](https://github.com/threatgrid/ctim/issues/383) to add `aliases` to `actor`. I would be happy to submit a PR for both of these btw. I would actually prefer to do it myself, if that's okay with y'all, so I can gain some familiarity with the CTIM code. I know you're still making a final decision, but just wanted to express that intent.

**Comment by ereteog** [comment]
yes you can move forward with that!
