### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctim#4]
Some basic examples that test the schemas.  When the test fail, that should indicate compatibility breakage and hint that a version bump will be required.

**Comment by yogsototh** [comment]
Thinking about this, it appears clear that to make such tests we need to keep a reference of the _old_ schemas to compare to the current schemas. Here are a list of possibilities I had in mind, and I like none of them:

- Copy the complete old schema definitions in the tests. As CTIM is mostly the schema definition it will feel strange and doesn't seems right to me.
- Have some kind of signature (for example I tried to make a `pr-str` on a schema and keep this string as reference. This causes some technical problems as there are anonymous functions which dont keep the same name at each new run for example `fn-453` when I made the first `pr-str` and during test time it became `fn-53342`. I imagine there will be many other subtle difficulties in trying to find a canonical representation of schemas other than the schemas themselves.
- May be use an external script which would be able to take advantage of the local git repository and keeping a reference commit to compare to. Such script should be able to load two different versions of CTIM. It might change some ns names to be able to run a `diff` between schemas. Also, I am not sure that the CI has the complete git history at its disposal.
- Use Clojars, which sounds very similar to git, except it might be easier to use in the CI environment. 

I tried to search the Internet on how other people manage this problem, but my google fu are weak. So any better idea would be really welcome.
