### ISSUE TITLE
Implement Relationship entity

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctim#40]
Need to allow people to make relations between objects (source, relation, destination)

Should contain:
- Source: URI to origin object
- Relation: a new vocabulary
- Destination: The subject object

**Comment by polygloton** [comment]
See also threatgrid/ctia#30

**Comment by craigbro** [comment]
I think this needs to be a BaseEntity, SourcableEntity and DescribableEntity

**Comment by polygloton** [comment]
I was thinking about "name", "source", and "related" to match http://cyboxproject.github.io/documentation/object-relationships/.  What do you think?

**Comment by polygloton** [comment]
Also consider [STIX 2.0 RC1](https://docs.google.com/document/d/1HJqhvzO35h62gQGPvghVRIAtQrZn3_J__0UcDAj-NXY/edit#)
