### ISSUE TITLE
TTP/ressources/tools schema looks ambiguous

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctim#51]
``` clojure
(s/defschema Resource
  "See http://stixproject.github.io/data-model/1.2/ttp/ResourceType/"
  (st/optional-keys
   {:tools (describe c/Tool "The tool leveraged by this TTP")
    :infrastructure (describe
                     Infrastructure
                     "infrastructure observed to have been utilized for cyber attack")
    :personas c/Identity}))
```

Here the `:tools`key is described as a single item, should we rename the key to `tool`or change `c/Tool`to `[c/Tool]` ?

**Comment by polygloton** [comment]
The name came from blindly following the [STIX 1.2 TTP spec](http://stixproject.github.io/data-model/1.0/ttp/ResourceType/).  I think you are right, we should rename it.

**Comment by polygloton** [comment]
It looks like STIX specifies "one or more" tools.

**Comment by AlexBaranosky** [comment]
@polygloton https://www.youtube.com/watch?v=QumxOQganfo

**Comment by polygloton** [comment]
Looks like @craigbro [changed](https://github.com/threatgrid/ctim/commit/14f7f2ae55785a3f0180b0d369c27c17e7735b9f#diff-3879963337638d063b997cdbf25a665cL56) it from [c/Tool] to c/Tool.  I thank that is as good as permission to rename it.

**Comment by polygloton** [comment]
@AlexBaranosky haha
