### ISSUE TITLE
Improve the generated markdown

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctim#65]
Iterate on improving the markdown that is generated by the flanders type definitions

- [x] Nested maps should be documented un-nested with links in the top level map
- [x] References should be markdown links, not just URIs
- [x] All maps should have a name, and most should have descriptions
- [x] Any URL in a description should be a markdown link
- [x] Add :comments to the nodes (developer notes in the documentation)
- [x] Truncate long schemas, like "(enum a b c ...", which can be done since the values are listed

Also do some simple refactoring

- [ ] Standardize map definitions (syntax evolved during conversion of CTIM)
  - [x] Use [Type] in entries instead of (seq-of Type)
  - [x] Use map/map-of/def-map-type consistently
  - [x] Use #{Type ...} in entries instead of (enum #{Type ...})
  - [x] def-entity-type should allow references to be defined

**Comment by polygloton** [comment]
- [ ] Add Usage Notes to leaf nodes

**Comment by polygloton** [comment]
- [ ] There should be an index page that points to the various generated documents
- [ ] Need to delete old schema docs in CTIM and CTIA (threatgrid/ctia#423)

**Comment by craigbro** [comment]
I think you should just make :description be markdown, that way if I want a link, I can write it out as markdown, and I get all the other markdown behavior.

**Comment by yogsototh** [comment]
I believe we hit the issue for :description used in swagger (which I don't think support markdown) and adding another field, :long-description that would be able to handle markdown and be used for more in depth documentation.

**Comment by craigbro** [comment]
Since markdown is just text, why is the lack of support for it in swagger an isue?

**Comment by yogsototh** [comment]
In swagger-ui the text describing a field is intended be "short".

For example this is what swagger-ui display when an user click on Model description:

~~~
Log {
tags (Array[string], optional): An optional list of strings ,
_event_type (string, optional): The type of event for example syslog, cisco_syslog, wsa_log ,
_format (string, optional): The optional logstash codec, default is plain another common is json ,
@timestamp (string): Event occured at ,
_collector (string): The name of the collector this event came through ,
_raw (string): The raw, original event text ,
@version (string): Event schema version ,
_source (string): The source, a file path, socket or url path or other identifier specific to _input ,
_encoding (string, optional): The character set of the event, default UTF-8 ,
_input (string): The name of the input module this event came via
}
~~~

If we write a long description, it will certainly be hard to read in swagger-ui.

But we also sometime need to be able to add a long, in-depth description.
Typically when we generate a documentation in another format than an interactive app.
Of course as for now, we use a middle man to generate "descriptions" in schemas we could apply a function that depending on the output (swagger or markdown documentation) could cut the description to some reasonable length.

**Comment by craigbro** [comment]
Well, the convention we have in other places is :short_description and :description, with :short_description being a pure string.  Why not use that?

**Comment by yogsototh** [comment]
yes, that feels right.

**Comment by polygloton** [comment]
We could truncate the description when we generate the schema that swagger sees (or modify it in some other way).

**Comment by polygloton** [comment]
Currently I am assuming that descriptions (and references) are markdown.

**Comment by craigbro** [comment]
@steve yah, I believe the convention we settled on in other places was the use :short_description if present, otherwise break on first sentence, or paragraph of the full description.
